FROM python:3.6.3-alpine3.6

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ADD ./requirements.txt /usr/src/app/requirements.txt

RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev

# install requirements
RUN pip install -r requirements.txt

# add app
ADD . /usr/src/app

CMD python manage.py runserver -h 0.0.0.0